// ═══════════════════════════════════════════════════════════════
// Admin Panel Themes — Design tokens for each theme
// Each theme defines CSS variables that control the entire admin UI
// ═══════════════════════════════════════════════════════════════

export interface AdminTheme {
  id: string;
  name: string;
  description: string;
  preview: { sidebar: string; bg: string; accent: string; card: string };
  mode: 'light' | 'dark';
  fonts: { heading: string; body: string; mono: string };
  tokens: Record<string, string>;
}

export const ADMIN_THEMES: AdminTheme[] = [
  {
    id: 'dsd-classic',
    name: 'DSD Classic',
    description: 'El tema original de DavidSon\'s Design. Tonos cálidos de madera con acentos dorados.',
    preview: { sidebar: '#2d2419', bg: '#FAF8F5', accent: '#C5A065', card: '#FFFFFF' },
    mode: 'light',
    fonts: { heading: "'Playfair Display', serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
    tokens: {
      '--admin-bg': '#FAF8F5',
      '--admin-surface': '#FFFFFF',
      '--admin-surface2': '#F5F3F0',
      '--admin-text': '#2d2419',
      '--admin-text-secondary': '#8B7355',
      '--admin-muted': '#B8A88A',
      '--admin-border': '#E8E0D4',
      '--admin-accent': '#C5A065',
      '--admin-accent-hover': '#B8933D',
      '--admin-accent-text': '#FFFFFF',
      '--admin-sidebar-bg': '#2d2419',
      '--admin-sidebar-text': '#E8E0D4',
      '--admin-sidebar-active': 'rgba(197,160,101,0.15)',
      '--admin-sidebar-accent': '#C5A065',
      '--admin-sidebar-border': 'rgba(255,255,255,0.08)',
      '--admin-sidebar-width': '260px',
      '--admin-success': '#16A34A',
      '--admin-error': '#DC2626',
      '--admin-warning': '#D97706',
      '--admin-info': '#2563EB',
      '--admin-card-radius': '12px',
      '--admin-button-radius': '8px',
      '--admin-input-radius': '8px',
      '--admin-shadow': '0 1px 3px rgba(0,0,0,0.06)',
      '--admin-shadow-lg': '0 4px 12px rgba(0,0,0,0.08)',
    },
  },
  {
    id: 'indigo-glass',
    name: 'Indigo Glass',
    description: 'Diseño luminoso con glassmorphism, sidebar rail compacto y acentos índigo.',
    preview: { sidebar: '#0f0f1a', bg: '#f5f5f7', accent: '#6366f1', card: '#FFFFFF' },
    mode: 'light',
    fonts: { heading: "'Inter', sans-serif", body: "'Inter', sans-serif", mono: "'JetBrains Mono', monospace" },
    tokens: {
      '--admin-bg': '#f5f5f7',
      '--admin-surface': '#FFFFFF',
      '--admin-surface2': '#f1f5f9',
      '--admin-text': '#0f172a',
      '--admin-text-secondary': '#64748b',
      '--admin-muted': '#94a3b8',
      '--admin-border': '#e2e8f0',
      '--admin-accent': '#6366f1',
      '--admin-accent-hover': '#4f46e5',
      '--admin-accent-text': '#FFFFFF',
      '--admin-sidebar-bg': '#0f0f1a',
      '--admin-sidebar-text': '#94a3b8',
      '--admin-sidebar-active': 'rgba(99,102,241,0.12)',
      '--admin-sidebar-accent': '#6366f1',
      '--admin-sidebar-border': 'rgba(255,255,255,0.06)',
      '--admin-sidebar-width': '72px',
      '--admin-success': '#10b981',
      '--admin-error': '#ef4444',
      '--admin-warning': '#f59e0b',
      '--admin-info': '#06b6d4',
      '--admin-card-radius': '12px',
      '--admin-button-radius': '8px',
      '--admin-input-radius': '8px',
      '--admin-shadow': '0 1px 3px rgba(0,0,0,0.04)',
      '--admin-shadow-lg': '0 8px 24px rgba(0,0,0,0.06)',
    },
  },
  {
    id: 'teal-noir',
    name: 'Teal Noir',
    description: 'Modo oscuro elegante con acentos teal. Orientado a analytics y datos.',
    preview: { sidebar: '#111114', bg: '#08080A', accent: '#14B8A6', card: '#111114' },
    mode: 'dark',
    fonts: { heading: "'Sora', sans-serif", body: "'DM Sans', sans-serif", mono: "'JetBrains Mono', monospace" },
    tokens: {
      '--admin-bg': '#08080A',
      '--admin-surface': '#111114',
      '--admin-surface2': '#1A1A1F',
      '--admin-text': '#E8E8EC',
      '--admin-text-secondary': '#9999A5',
      '--admin-muted': '#6B6B78',
      '--admin-border': '#222228',
      '--admin-accent': '#14B8A6',
      '--admin-accent-hover': '#0D9488',
      '--admin-accent-text': '#08080A',
      '--admin-sidebar-bg': '#111114',
      '--admin-sidebar-text': '#E8E8EC',
      '--admin-sidebar-active': 'rgba(20,184,166,0.12)',
      '--admin-sidebar-accent': '#14B8A6',
      '--admin-sidebar-border': '#222228',
      '--admin-sidebar-width': '260px',
      '--admin-success': '#16A34A',
      '--admin-error': '#ef4444',
      '--admin-warning': '#f59e0b',
      '--admin-info': '#6366f1',
      '--admin-card-radius': '10px',
      '--admin-button-radius': '8px',
      '--admin-input-radius': '8px',
      '--admin-shadow': '0 1px 3px rgba(0,0,0,0.3)',
      '--admin-shadow-lg': '0 8px 24px rgba(0,0,0,0.4)',
    },
  },
  {
    id: 'coral-forge',
    name: 'Coral Forge',
    description: 'Modo oscuro con toques cálidos de coral y naranja. Escala de color completa.',
    preview: { sidebar: '#0F1114', bg: '#08090B', accent: '#F97316', card: '#0F1114' },
    mode: 'dark',
    fonts: { heading: "'Sora', sans-serif", body: "'DM Sans', sans-serif", mono: "'JetBrains Mono', monospace" },
    tokens: {
      '--admin-bg': '#08090B',
      '--admin-surface': '#0F1114',
      '--admin-surface2': '#161A1F',
      '--admin-text': '#E8ECF0',
      '--admin-text-secondary': '#9BA5B0',
      '--admin-muted': '#6B7A85',
      '--admin-border': '#1A2228',
      '--admin-accent': '#F97316',
      '--admin-accent-hover': '#FB923C',
      '--admin-accent-text': '#FFFFFF',
      '--admin-sidebar-bg': '#0F1114',
      '--admin-sidebar-text': '#E8ECF0',
      '--admin-sidebar-active': 'rgba(249,115,22,0.12)',
      '--admin-sidebar-accent': '#F97316',
      '--admin-sidebar-border': '#1A2228',
      '--admin-sidebar-width': '72px',
      '--admin-success': '#22C55E',
      '--admin-error': '#EF4444',
      '--admin-warning': '#F59E0B',
      '--admin-info': '#3B82F6',
      '--admin-card-radius': '10px',
      '--admin-button-radius': '8px',
      '--admin-input-radius': '8px',
      '--admin-shadow': '0 1px 3px rgba(0,0,0,0.3)',
      '--admin-shadow-lg': '0 8px 24px rgba(0,0,0,0.4)',
    },
  },
  {
    id: 'sage-command',
    name: 'Sage Command',
    description: 'Diseño oscuro limpio con keyboard shortcuts, spotlight search y paneles modulares.',
    preview: { sidebar: '#111114', bg: '#08080A', accent: '#14B8A6', card: '#111114' },
    mode: 'dark',
    fonts: { heading: "'Sora', sans-serif", body: "'DM Sans', sans-serif", mono: "'JetBrains Mono', monospace" },
    tokens: {
      '--admin-bg': '#08080A',
      '--admin-surface': '#111114',
      '--admin-surface2': '#1A1A1F',
      '--admin-text': '#E8E8EC',
      '--admin-text-secondary': '#9999A5',
      '--admin-muted': '#6B6B78',
      '--admin-border': '#222228',
      '--admin-accent': '#14B8A6',
      '--admin-accent-hover': '#0D9488',
      '--admin-accent-text': '#08080A',
      '--admin-sidebar-bg': '#111114',
      '--admin-sidebar-text': '#E8E8EC',
      '--admin-sidebar-active': 'rgba(20,184,166,0.12)',
      '--admin-sidebar-accent': '#14B8A6',
      '--admin-sidebar-border': '#222228',
      '--admin-sidebar-width': '240px',
      '--admin-success': '#16A34A',
      '--admin-error': '#DC2626',
      '--admin-warning': '#D97706',
      '--admin-info': '#2563EB',
      '--admin-card-radius': '10px',
      '--admin-button-radius': '8px',
      '--admin-input-radius': '8px',
      '--admin-shadow': '0 1px 3px rgba(0,0,0,0.3)',
      '--admin-shadow-lg': '0 8px 24px rgba(0,0,0,0.4)',
    },
  },
];

export const getThemeById = (id: string): AdminTheme =>
  ADMIN_THEMES.find(t => t.id === id) || ADMIN_THEMES[0];
